### ISSUE TITLE
Still Active?

### ISSUE THREAD

**Issue by kershnerd** [nyorain/ny#8]
Is this still an active project?  I'm looking to find/create a cross platform window abstraction in Windows and MacOS (and more).

**Comment by nyorain** [comment]
Not finding much time to work on this these days, sorry. It doesn't yet have any macOS support (PRs as always welcome though :D) and tbh i probably wouldn't recommend to use it in serious projects (yet?). I can recommend GLFW when you plan to use opengl or vulkan. Otherwise SDL might be worth looking into. Creating your own obviously is a nice project as well, I learned quite a bit writing this.

**Comment by kershnerd** [comment]
OK... thanks!
